name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # 只有main分支推送代码，才触发打包部署
  workflow_dispatch: # 支持在Github网页手动点按钮触发部署
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 拉取代码
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: 打包构建
        run: pnpm build
      - name: 上传打包产物dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到Github Pages
        id: deployment
        uses: actions/deploy-pages@v4